namespace: wisecow

replicaCount: 2

image:
  repository: shikhrshukla/wisecow
  tag: e4e743c1f4c35dbea0d5a51a1ac8671aa58fcbe6
  pullPolicy: IfNotPresent

container:
  port: 4499

service:
  type: NodePort
  port: 80
  nodePort: 30499

ingress:
  name: sample
  enabled: true
  host: wisecow.local
  secretName: wisecow-tls

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 3
