name: Wisecow CI Pipeline with Helm Updation

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Screenshots/**'
      - 'README.md'
      - 'helm/templates/**'
      - 'helm/values.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Validate Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile || true

  docker_build_and_push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Wisecow Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

  update_helm_chart:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.TOKEN_GIT }}

      - name: Update Helm Chart with Latest Image Tag
        run: |
          sed -i "s|tag: .*|tag: ${{ github.sha }}|g" ./helm/values.yaml

      - name: Commit and Push Updated Helm Chart
        run: |
          git config --global user.name "Shikhrshukla"
          git config --global user.email "shikhar31690.1@gmail.com"
          git add ./helm/values.yaml
          git commit -m "Update Helm chart image tag to ${{ github.sha }}"
          git push
